import React from "react";

export default function PrivacyPolicy() {
  return (
    <div className="auth-page" style={{ alignItems: "flex-start", padding: "40px 20px" }}>
      <div className="card fade-up" style={{ maxWidth: 720, margin: "0 auto", padding: "36px 40px" }}>
        <div className="auth-logo-row">
          <div className="logo-mark">C</div>
          <div className="logo-word">Clarity</div>
        </div>
        <h1 className="auth-title">Privacy Policy</h1>
        <p className="auth-sub">Last updated: 2026-07-10</p>

        <p>
          Clarity ("we", "us", "our") is operated by Haoze Li, an individual sole trader based in
          Australia. Clarity is a maths tutoring platform intended for use by tutors and students
          located in Australia. This policy explains how we collect, use, store, and protect personal
          information in connection with the Clarity application, in accordance with the Australian
          Privacy Principles (APPs) under the <em>Privacy Act 1988</em> (Cth).
        </p>

        <h2>1. Who this policy covers</h2>
        <p>
          This policy applies to anyone who creates a Clarity account, as a tutor or a student, and to
          information collected about students who are added to a tutor's roster.
        </p>

        <h2>2. Information we collect</h2>
        <ul>
          <li>
            <strong>Account information</strong>: name, email address, and account role (tutor or
            student), collected at sign-up via Firebase Authentication (email/password or Google
            sign-in).
          </li>
          <li>
            <strong>Roster relationships</strong>: the tutor-student pairings a tutor creates on their
            roster.
          </li>
          <li>
            <strong>Class information</strong>: class titles, notes, schedules, attendee lists, and any
            files a tutor attaches as class materials.
          </li>
          <li>
            <strong>Task information</strong>: task titles, notes, due dates, student submissions, and
            any files attached to a task by either a tutor or a student.
          </li>
          <li>
            <strong>Q&amp;A messages</strong>: the content of questions and answers exchanged between a
            tutor and a student through the app's Q&amp;A feature.
          </li>
          <li>
            <strong>Zoom connection information</strong> (tutors only, optional): if a tutor chooses to
            connect their Zoom account, we store the Zoom account email associated with that connection
            and an encrypted copy of the OAuth access/refresh tokens Zoom issues, so we can create a Zoom
            meeting on the tutor's behalf when they schedule a class. We do not access anything else in a
            tutor's Zoom account beyond what is needed to create these meetings.
          </li>
          <li>
            <strong>Technical/log data</strong>: standard infrastructure logs generated by Google
            Cloud/Firebase as part of operating the service, not directly reviewed by us except when
            investigating a fault or a reported security issue.
          </li>
        </ul>
        <p>We do not collect payment information, government identifiers, or health information.</p>

        <h2>3. How we use this information</h2>
        <p>
          We use personal information only to operate Clarity's core features: creating and managing
          accounts, scheduling and displaying classes, assigning and tracking tasks, enabling Q&amp;A
          between tutors and students, and (where a tutor opts in) creating Zoom meetings for scheduled
          classes. We do not use personal information for advertising, and we do not sell personal
          information to any third party.
        </p>

        <h2>4. Who we share information with</h2>
        <ul>
          <li>
            <strong>Google (Firebase / Google Cloud)</strong>: our infrastructure provider. All account
            data, class/task content, and file attachments are stored using Firebase Authentication,
            Firestore, and Firebase Storage, and our backend logic runs on Google Cloud Functions. Google
            acts as our service provider and does not use this data for its own purposes.
          </li>
          <li>
            <strong>Zoom</strong>: only for tutors who choose to connect their Zoom account, and only to
            the extent needed to create a meeting for a scheduled class (meeting topic, scheduled time,
            and duration are sent to Zoom's API). Zoom's own privacy policy governs Zoom's handling of
            that meeting data once created.
          </li>
        </ul>
        <p>
          We do not share personal information with any other third party, and we do not disclose it for
          marketing purposes.
        </p>

        <h2>5. Overseas storage and processing</h2>
        <p>
          Clarity is built on Google Cloud/Firebase infrastructure. While the service is intended for
          Australian users, the underlying infrastructure may store and process personal information
          outside Australia, including in the United States (for example, the backend functions that
          handle Zoom meeting creation currently run in a United States Google Cloud region). By using
          Clarity, you acknowledge that your information may be processed overseas as described here.
          We choose Google Cloud/Firebase specifically because of its strong security practices, and we
          take reasonable steps to ensure information is protected consistently with the Australian
          Privacy Principles regardless of where it is processed.
        </p>

        <h2>6. Data security</h2>
        <p>
          Personal information is protected using access controls enforced at the database level
          (Firestore and Storage security rules), so that a user can only access data related to their
          own tutor-student relationships. Zoom OAuth tokens receive an additional layer of encryption
          before being stored.
        </p>

        <h2>7. Data retention and deletion</h2>
        <p>
          We retain personal information for as long as an account remains active, so the app can
          continue to function (e.g., displaying class history). If you would like your account or
          personal information deleted, contact us at the email below and we will action the request
          manually — Clarity does not yet have a fully self-service account-deletion feature.
        </p>

        <h2>8. Access and correction</h2>
        <p>
          You can request access to, or correction of, the personal information we hold about you at any
          time by contacting us at the email below. We will respond within a reasonable time.
        </p>

        <h2>9. Children and students under 18</h2>
        <p>
          Clarity is intended to be used by students aged 13 or older, or by younger students with the
          involvement and consent of a parent or guardian. Tutors are responsible for ensuring they have
          appropriate consent from a parent or guardian before adding a student who is a minor to their
          roster. Clarity does not currently perform automated age verification at sign-up; we rely on
          the person registering the account (or the tutor adding a student) to act honestly and
          appropriately here.
        </p>

        <h2>10. Complaints</h2>
        <p>
          If you believe we have mishandled your personal information, you can contact us directly at
          the email below. If you are not satisfied with our response, you have the right to lodge a
          complaint with the Office of the Australian Information Commissioner (OAIC) at{" "}
          <a href="https://www.oaic.gov.au" target="_blank" rel="noreferrer">
            www.oaic.gov.au
          </a>
          .
        </p>

        <h2>11. Changes to this policy</h2>
        <p>
          We may update this policy from time to time as Clarity's features change. The "Last updated"
          date at the top of this document will reflect the most recent revision.
        </p>

        <h2>12. Contact us</h2>
        <p>
          For any privacy question, request, or complaint, contact:
          <br />
          <strong>Haoze Li</strong>
          <br />
          Email: alexliwork123@gmail.com
        </p>

        <div className="auth-footer">
          <a href="/">Back to Clarity</a>
        </div>
      </div>
    </div>
  );
}
